/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2016-01-17 11:22:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.adminMgr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userMgr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script>\r\n");
      out.write("\t//jquery validate表单验证\r\n");
      out.write("\t$().ready(function() {\r\n");
      out.write("\t\t$(\"#myform\").validate({\r\n");
      out.write("\t\t\trules : {\r\n");
      out.write("\t\t\t\tloginName : \"required\",\r\n");
      out.write("\t\t\t\tpassword : {\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\tminlength : 6\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tuserName : \"required\",\r\n");
      out.write("\t\t\t\ttel : {\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\tmobile : true\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\temail : {\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\temail : true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tmessages : {\r\n");
      out.write("\t\t\t\tloginName : \"请输入帐号\",\r\n");
      out.write("\t\t\t\tpassword : {\r\n");
      out.write("\t\t\t\t\trequired : \"请输入密码\",\r\n");
      out.write("\t\t\t\t\tminlength : \"至少为六位\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tuserName : \"请输入账户号\",\r\n");
      out.write("\t\t\t\temail : {\r\n");
      out.write("\t\t\t\t\trequired : \"请输入Email地址\",\r\n");
      out.write("\t\t\t\t\temail : \"请输入正确的email地址\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\ttel : {\r\n");
      out.write("\t\t\t\t\trequired : \"请输入手机号\",\r\n");
      out.write("\t\t\t\t\tmobile : \"手机格式错误\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar $table = $('#table');\r\n");
      out.write("\t\t$table.bootstrapTable({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sysmgr/pageQueryUser',\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tsidePagination : 'server',\r\n");
      out.write("\t\t\tqueryParamsType : 'self',\r\n");
      out.write("\t\t\tqueryParams : function(params) {\r\n");
      out.write("\t\t\t\tvar pageParam = {\r\n");
      out.write("\t\t\t\t\tpage : params.pageNumber,\r\n");
      out.write("\t\t\t\t\trows : params.pageSize\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tvar searchParam = $(\".form-search\").getSearchFormObject();\r\n");
      out.write("\t\t\t\treturn $.extend(pageParam, searchParam);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpageList : [ 5, 10, 50 ],\r\n");
      out.write("\t\t\tpageSize : 5,\r\n");
      out.write("\t\t\tpageNumber : 1,\r\n");
      out.write("\t\t\theight : getHeight(),\r\n");
      out.write("\t\t\tcolumns : [ {\r\n");
      out.write("\t\t\t\tfield : 'userId',\r\n");
      out.write("\t\t\t\ttitle : '编号',\r\n");
      out.write("\t\t\t\twidth : '10%',\r\n");
      out.write("\t\t\t\talign : 'center'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'loginName',\r\n");
      out.write("\t\t\t\ttitle : '登录名',\r\n");
      out.write("\t\t\t\twidth : '15%',\r\n");
      out.write("\t\t\t\talign : 'center'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'tel',\r\n");
      out.write("\t\t\t\ttitle : '手机号',\r\n");
      out.write("\t\t\t\twidth : '20%',\r\n");
      out.write("\t\t\t\talign : 'center'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'email',\r\n");
      out.write("\t\t\t\ttitle : '邮箱',\r\n");
      out.write("\t\t\t\twidth : '25%',\r\n");
      out.write("\t\t\t\talign : 'center'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'userName',\r\n");
      out.write("\t\t\t\ttitle : '姓名',\r\n");
      out.write("\t\t\t\twidth : '20%',\r\n");
      out.write("\t\t\t\talign : 'center'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'userId',\r\n");
      out.write("\t\t\t\ttitle : '操作',\r\n");
      out.write("\t\t\t\tformatter : operateFormatter,\r\n");
      out.write("\t\t\t\tevents : operateEvents,\r\n");
      out.write("\t\t\t\twidth : '10%',\r\n");
      out.write("\t\t\t\talign : 'center'\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$table.on('load-success.bs.table', function(data) {\r\n");
      out.write("\t\t\t//console.log(\"load-success...\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 保存\r\n");
      out.write("\t\t$(\"#btnSave\").click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tif ($(\"#myform\").valid()) {\r\n");
      out.write("\t\t\t\t\t\tvar obj = $(\".form-save\").getFormObject();\r\n");
      out.write("\t\t\t\t\t\t$.ajaxPostJson(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sysmgr/saveOrUpdateUser\", obj,\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#table').bootstrapTable(\"refresh\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#myModal').modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tshowMessage(\"操作成功!\");\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t// 新增\r\n");
      out.write("\t\t$(\".add\").click(function() {\r\n");
      out.write("\t\t\t$(\".form-save\").clearForm();\r\n");
      out.write("\t\t\t$('#myModalLabel').html('新增');\r\n");
      out.write("\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//查询\r\n");
      out.write("\t\t$(\"#btnSearch\").click(function() {\r\n");
      out.write("\t\t\t$table.bootstrapTable(\"selectPage\", 1);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\twindow.operateEvents = {\r\n");
      out.write("\t\t'click .edit' : function(e, value, row, index) {\r\n");
      out.write("\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t\t$('#myModalLabel').html('修改');\r\n");
      out.write("\t\t\t$.ajaxPostJson(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sysmgr/getUserById/\" + row.userId, {},\r\n");
      out.write("\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".form-save\").setFormObject(result);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t'click .remove' : function(e, value, row, index) {\r\n");
      out.write("\t\t\t$('#confirmModal').modal('show');\r\n");
      out.write("\t\t\t$(\"#btnConfirm\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t$.ajaxPostJson(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sysmgr/deleteUser/\" + row.userId, {},\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#table').bootstrapTable(\"refresh\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#confirmModal').modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tshowMessage(\"操作成功!\");\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction getHeight() {\r\n");
      out.write("\t\treturn $(window).height() - $('#toolbarDiv').outerHeight(true) - 150;\r\n");
      out.write("\t}\r\n");
      out.write("\t// 修改、删除\r\n");
      out.write("\tfunction operateFormatter(value, row, index) {\r\n");
      out.write("\t\treturn [\r\n");
      out.write("\t\t\t\t'<a class=\"edit\" href=\"javascript:void(0)\" title=\"编辑\"><i class=\"glyphicon glyphicon-edit\"></i></a>',\r\n");
      out.write("\t\t\t\t'<a class=\"remove\" href=\"javascript:void(0)\" title=\"删除\"><i class=\"glyphicon glyphicon-remove\"></i></a>', ]\r\n");
      out.write("\t\t\t\t.join('&nbsp;&nbsp;');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\" id=\"toolbarDiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-md add\">添加</button>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- data-toggle=\"modal\" data-target=\"#myModal\" -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-9 col-lg-9 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"form-search form-inline\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"search_userName\">姓名：</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"search_userName\" placeholder=\"请输入姓名\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"search_tel\">手机号：</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"search_tel\" placeholder=\"请输入手机号\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id=\"btnSearch\">查询</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<table id=\"table\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"table table-bordered table-striped table-condensed table-hover\">\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Modal 新增修改-->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">添加</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form-save form-horizontal\" method=\"post\" action=\"#\"\r\n");
      out.write("\t\t\t\t\t\tid=\"myform\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"userId\" name=\"userId\"/>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"loginName\" class=\"col-sm-4 control-label\">登录名：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"loginName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"loginName\" placeholder=\"登录名\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\" class=\"col-sm-4 control-label\">密码：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"password\" placeholder=\"密码\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"userName\" class=\"col-sm-4 control-label\">姓名：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"userName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"userName\" placeholder=\"姓名\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"tel\" class=\"col-sm-4 control-label\">手机号：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"tel\" name=\"tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"手机号\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"email\" class=\"col-sm-4 control-label\">邮箱：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"邮箱\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btnSave\">保存</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/adminMgr/userMgr.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/views/adminMgr/userMgr.jsp(3,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
