/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2016-01-17 09:01:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sysmgr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-store\" />\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"Expires\" content=\"0\" />\r\n");
      out.write("<title>管理员登录</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/css/login.css\" type=\"text/css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div id=\"loginbox\">\r\n");
      out.write("\t\t\t<form id=\"loginForm\" class=\"form-vertical text-center\" method=\"post\"\r\n");
      out.write("\t\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login\" style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i></span> <input type=\"text\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\tname=\"name\" class=\"form-control input-medium required\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"登录名\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i></span> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\tid=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control input-medium required\" placeholder=\"密码\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-sunglasses\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t <select  id=\"identity\" name=\"identity\" class=\"form-control input-medium required\" style=\"width:120px !important;border-top-right-radius:4px !important;border-bottom-right-radius:4px !important;\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t\t\t \t<option value=\"0\">管理员</option>\r\n");
      out.write("\t\t\t\t\t\t \t<option value=\"1\">超级管理员</option>\r\n");
      out.write("\t\t\t\t\t\t </select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 验证码 -->\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-picture\"></i></span>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"validateCode\" name=\"validateCode\" class=\"form-control input-captcha\" placeholder=\"验证码\" style=\"width:100px !important;border-top-right-radius:4px !important;border-bottom-right-radius:4px !important;\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/validateCodeServlet\" onclick=\"$(this).attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/validateCodeServlet?'+new Date().getTime());\" style=\"margin-top:3px;\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					String error = (String) request.getAttribute("error");
					if(error!=null){
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"input-group alert alert-danger input-medium controls\">\r\n");
      out.write("\t\t\t\t\t<button class=\"close\" data-dismiss=\"alert\">×</button>");
      out.print(error );
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-actions form-line-split\">\r\n");
      out.write("\t\t\t\t\t<span class=\"pull-center\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary\" style=\"width: 116px;\" value=\"登 录\" />\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"pull-center\"> <input type=\"reset\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-default\" style=\"width: 116px;\" id=\"btnRecover\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"忘记密码\" />\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<!-- ======忘记密码div====== -->\r\n");
      out.write("\t\t\t<form id=\"recoverForm\" class=\"form-vertical\"\r\n");
      out.write("\t\t\t\taction=\"javascript:void(0);\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>请您填写Email,作为证据找回密码.</p>\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-envelope\"></i></span> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" placeholder=\"请输入E-mail\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-line-split-2\">\r\n");
      out.write("\t\t\t\t\t<span class=\"pull-center\"> <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"flip-link\" id=\"btnReturnLogin\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default\" style=\"width: 116px !important;\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"返回\" /></a>\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"pull-center\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary\" style=\"width: 116px !important;\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"确定\" />\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" id=\"error\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/* $(\"#loginForm\").validate({\r\n");
      out.write("\t\t\t\trules: {\r\n");
      out.write("\t\t\t\t\tname: {required:true},\r\n");
      out.write("\t\t\t\t\tpassword: {required:true},\r\n");
      out.write("\t\t\t\t\tvalidateCode: {required:true}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmessages: {\r\n");
      out.write("\t\t\t\t\tname: {required: \"请填写用户名.\"},password: {required: \"请填写密码.\"},\r\n");
      out.write("\t\t\t\t\tvalidateCode: {remote: \"验证码不正确.\", required: \"请填写验证码.\"}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); */ \r\n");
      out.write("\t\t\t//$(\"#loginForm\").validate();\r\n");
      out.write("\t\t\tvar loginForm = $('#loginForm');\r\n");
      out.write("\t\t\tvar recoverForm = $('#recoverForm');\r\n");
      out.write("\t\t\tvar speed = 400;\r\n");
      out.write("\t\t\t$('#btnRecover').click(function() {\r\n");
      out.write("\t\t\t\tloginForm.fadeTo(speed, 0.01).css('z-index', '100');\r\n");
      out.write("\t\t\t\trecoverForm.fadeTo(speed, 1).css('z-index', '200');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#btnReturnLogin').click(function() {\r\n");
      out.write("\t\t\t\trecoverForm.fadeTo(speed, 0.01).css('z-index', '100');\r\n");
      out.write("\t\t\t\tloginForm.fadeTo(speed, 1).css('z-index', '200');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//回车键提交\r\n");
      out.write("\t\t\tdocument.onkeydown = function(evt){\r\n");
      out.write("\t\t\t   var evt = window.event?window.event:evt;\r\n");
      out.write("\t\t\t   if (evt.keyCode==13) {\r\n");
      out.write("\t\t\t    \t\tif(loginForm.css(\"zIndex\")==200){\r\n");
      out.write("\t\t\t\t           document.forms[\"loginForm\"].submit();\r\n");
      out.write("\t\t\t    \t\t}else{\r\n");
      out.write("\t\t\t    \t\t\t$(\"#btnReset\").click();\r\n");
      out.write("\t\t\t    \t\t} \t\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/sysmgr/login.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/views/sysmgr/login.jsp(3,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
